spring:
  application:
    name: ABC-SERVICE
    
eureka:
  instance:
    appname: ABC-SERVICE
  client:    
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 8000  