spring:
  datasource:
    username: postgres
    password: postgre
    url: jdbc:postgresql://localhost:5432/test_cloud?serverTimezone=UTC
  application:
    name: CONFIG-SERVICE
eureka:
  instance:
    appname: CONFIG-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 7777